# Generated by Django 4.0.5 on 2022-06-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0002_remove_file_upload_file_file_upload_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_upload',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to=''),
        ),
    ]
